## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - ./build-docs.sh prettyurls
      after_success: skip
